name: taskify
description: "Your Task Simplified."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.20.1
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  cupertino_icons: ^1.0.8
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  network_info_plus: ^4.1.0
  shelf_router: ^1.1.3
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Fixed indentation here
  http: ^1.1.0


# Flutter launcher icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/taskify.png"  # Updated to match your asset name

flutter:
  uses-material-design: true
  assets:
    - assets/taskify_logo.png
    - assets/web/
    - assets/web/index.html